### PR TITLE
Support for Symfony 4

### PR DESCRIPTION
**Pull request by Nyholm**
#SymfonyConHackday2017

### CODE REVIEW

**Comment by DavertMik** [comment]
Wow, thank you! Getting ready for Symfony4!

**Comment by DavertMik** [comment]
Hey, we are trying to get support for Codeception. Maybe you could you help with corresponding PR? https://github.com/Codeception/Codeception/pull/4580 as well

**Comment by davidcochrum** [comment]
Is it just me or did this merge not yet make it into a release tag?

**Comment by alec-w** [comment]
@davidcochrum doesn't like like it has. Really want to use this in a project to improve unit tests but other parts of our project require symfony 4.

**Pull request merged**
