### PR TITLE
Add stacked stub support

### PR DESCRIPTION
**Pull request by torreytsui**
Please see the test case.

### CODE REVIEW

**Comment by DavertMik** [comment]
Thanks for PR!

Sorry I didn't understand the use case. Is that like inheriting from redeclared methods?
Actually I was expected that stacked calls would be like:

```
getName() => 'tsui'
getName() => 'tt'
getName() => null
```

But looks I got the idea, but I didn't get the use case for it, so to update documentation for it. 
If you can - please add its usage example to docs (please use corresponding docblocks for that, do not update *.md in docs, as they are generated)

**Comment by torreytsui** [comment]
Thanks for you reply :smile:

I have added a docblock for the example (https://github.com/Codeception/AspectMock/pull/91/files#diff-c9b7c3e18d6822e921c243b89c999499R85).

Sorry, the example in the test case was not clear enough to demonstrate the use case.
The example in the doc will be better hopefully.

```
class User {
    public function getGroup() { return 'guest'; }
}
$user = new User;
```

So, it is for conflicted stubs, when a test double has been redefined.
```
$stub1 = function () { 
    return 'user';
};
$stub2 = function ($supersede = false) { 
    return $supersede ? 'root' : __AM_CONTINUE__; 
};
test::double('User', ['getGroup' => $stub1]);
test::double('User', ['getGroup' => $stub2]);
```

### Without stacked stubs
Currently, `$stub2` will take place on `$user->getGroup()` call.
```
$user->getGroup(true) // => root
$user->getGroup() // => guest
```

### Stacked stubs
When a test double is redefined, it has been replaced. And in the example, `$stub2` replace `$stub1`.
The stacked stubs basically is to allow a chain of responsibly pass through every conflicted stubs until a result returns.
So, the result will look like this:
```
$user->getGroup(true) // => root (handled by $stub2)
$user->getGroup() // => user (handled by $stub2 and then $stub1)
```
The `$user->getGroup()` first handled by $stub2 and it give up by returning `__AM_CONTINUE__`, $stub1 then take place and return "user".

### Drawbacks
* It is backward incompatible. As `__AM_CONTINUE__` currently implies *returning control to the real subject*. But this commit will change it to *giving up control*. As a result, it cannot return control to the real subject until every conflicted stubs are returning `__AM_CONTINUE__`.
* The use case of stacked stubs may not be common.

**Comment by DavertMik** [comment]
Ok, I think there can be usecases for that. 2.0.0 release is the right time to accept breaking change. The on;y thing which should be done here is documentation. I will update it

**Comment by DavertMik** [comment]
Thank you

**Comment by DavertMik** [comment]
I had to revert it as it fails for cases where you passes values like 

```
'getIntegers' => [1,2,3]
```

**Pull request merged**
