### PR TITLE
return void (fixes issue #123)

### LINKED ISSUE #123: return void - php7.1 feature broken
when i declare method like
`public function foo() : void { $foo = 3; }`
then as soon as that method was parsed (with extra code was injected there by aspectmock/goaop) i get the exception `PHP Fatal error:  A void function must not return a value in …`

i tried upgrading to aspectmock dev-master and goaop 2.1, but it didn't help

### PR DESCRIPTION
**Pull request by zuozp8**
there musn't be `return …;` statement in method that is declared to return void

### CODE REVIEW

**Comment by zuozp8** [comment]
#123

**Comment by zuozp8** [comment]
#123

**Comment by zuozp8** [comment]
i didnt find any test covering BeforeMockTransformer

**Comment by zuozp8** [comment]
@DavertMik could you merge it?

**Comment by sergeyklay** [comment]
As you can see the tests fails

**Comment by zuozp8** [comment]
Master is failing
https://travis-ci.org/Codeception/AspectMock/jobs/242577873 :(

14.06.2017 16:05 "Serghei Iakovlev" <notifications@github.com> napisał(a):

**Comment by wirwolf** [comment]
The problem is actual!

**Comment by SenseException** [comment]
@zuozp8 Can you please rebase from master and run the tests again? The build of master is clear now.

**Comment by zuozp8** [comment]
@DavertMik could you merge it?

**Comment by DavertMik** [comment]
Yes, thank you!

**Pull request merged**
